name: hugo-project

services:
  http:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
  make_html:
    build:
      context: ./
      dockerfile: ./make_html/Dockerfile
    volumes:
      - ../html:/html
